# Generated by Django 4.2.4 on 2023-09-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Картинка'),
        ),
    ]
